name: Flutter Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME for Gradle
        run: echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - name: Clean build artifacts
        run: flutter clean

      - name: flutter pub get
        run: flutter pub get

      - name: flutter format
        run: flutter format --set-exit-if-changed .

      - name: flutter analyze
        run: flutter analyze